# -*- coding: utf-8 -*-
# vim: set fileencoding=utf-8
version: '3.8'
services:
  ad-dc:
    privileged: true
    entrypoint: docker-entrypoint.sh
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    build:
      context: .
      cache_from: ["debian","buster"]
      dockerfile: Dockerfile
      labels:
        de.hjcms.label: "SAMBA"
        de.hjcms.description: "Samba Active Directory Domain Controller"
        de.hjcms.license: "GNU/GPLv3"

#EOF
