# -*- coding: utf-8 -*-
# vim: set fileencoding=utf-8
version: '3.8'
services:
  ad-dc:
    privileged: true
    environment:
      ## usable vars for domain provisioning
      - "AD_HOSTNAME=ad.smb.virt"
      - "AD_PASSWORD=P@55word"
      - "AD_DEBUGLEVEL=3"
    entrypoint: /usr/local/bin/domain-provision.sh
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      ## Kerberos
      - "88:88/tcp"
      - "88:88/udp"
      ## DCE/RPC Locator Service
      - "135:135/tcp"
      ## Network Session Browsing
      - "139:139/tcp"
      ## LDAP
      - "389:389/tcp"
      - "389:389/udp"
      ## SMB over TCP
      - "445:445/tcp"
      ## Kerberos kpasswd
      - "464:464/tcp"
      - "464:464/udp"
      ## LDAPS
      - "636:636/tcp"
      ## Global Catalog
      - "3268:3268/tcp"
      ## Global Catalog (SSL)
      - "3269:3269/tcp"
    build:
      context: .
      cache_from: ["debian","buster"]
      dockerfile: Dockerfile
      labels:
        de.hjcms.label: "SAMBA"
        de.hjcms.description: "Samba Active Directory Domain Controller"
        de.hjcms.license: "GNU/GPLv3"
        de.hjcms.swarm.node: "ad-dc"

#EOF
